### ISSUE TITLE
parse_events issue

### ISSUE THREAD

**Issue by ericleb** [fabriceb/gcalcron#13]
Any idea why it won't work for me, I use Python 2.7 and I believe I have all the required libraires:
python -m doctest -v gcalcron.py
Trying:
    g = GCalAdapter()
Expecting nothing
ok
Trying:
    g.get_query(datetime.datetime(2011, 6, 19, 14, 0), datetime.datetime(2011, 6, 26, 14, 0), datetime.datetime(2011, 6, 18, 14, 0))
Expecting:
    {'orderBy': 'updated', 'showDeleted': True, 'calendarId': None, 'timeMin': '2011-06-19T14:00:00', 'updatedMin': '2011-06-18T14:00:00', 'timeMax': '2011-06-26T14:00:00', 'fields': 'items(description,end,id,start,status,summary,updated)', 'singleEvents': True, 'maxResults': 1000}
ok
Trying:
    datetime_to_at(datetime.datetime(2011, 6, 18, 12, 0))
Expecting:
    '12:00 Jun 18'
ok
Trying:
    parse_commands("echo 'Wake up!'\n+10: echo 'Wake up, you are 10 minutes late!'", datetime.datetime(3011, 6, 19, 8, 30), datetime.datetime(3011, 6, 19, 9, 0))
Expecting:
    [{'exec_time': datetime.datetime(3011, 6, 19, 8, 30), 'command': "echo 'Wake up!'"}, {'exec_time': datetime.datetime(3011, 6, 19, 8, 40), 'command': "echo 'Wake up, you are 10 minutes late!'"}]
ok
Trying:
    parse_commands("Turn on lights\nend -10: Dim lights\nend: Turn off lights", datetime.datetime(3011, 6, 19, 18, 30), datetime.datetime(3011, 6, 19, 23, 0))
Expecting:
    [{'exec_time': datetime.datetime(3011, 6, 19, 18, 30), 'command': 'Turn on lights'}, {'exec_time': datetime.datetime(3011, 6, 19, 22, 50), 'command': 'Dim lights'}, {'exec_time': datetime.datetime(3011, 6, 19, 23, 0), 'command': 'Turn off lights'}]
ok
Trying:
    parse_events([{u'status': u'confirmed', u'updated': u'2013-12-22T19:49:13.750Z', u'end': {u'dateTime': u'2013-12-23T02:00:00+01:00'}, u'description': u'-60: start_heating.py\n0: turn_music_on.py\n+30: stop_heating.py', u'summary': u'Wakeup', u'start': {u'dateTime': u'2013-12-23T01:00:00+01:00'}, u'id': u'olbia2urfm1ns0h88v4u0d9a5g'}])
Expecting:
    [{'commands': [{'exec_time': datetime.datetime(2013, 12, 23, 0, 0), 'command': u'start_heating.py'}, {'exec_time': datetime.datetime(2013, 12, 23, 1, 0), 'command': u'0: turn_music_on.py'}, {'exec_time': datetime.datetime(2013, 12, 23, 1, 30), 'command': u'stop_heating.py'}], 'uid': u'olbia2urfm1ns0h88v4u0d9a5g'}]

---

File "gcalcron.py", line 358, in gcalcron.parse_events
Failed example:
    parse_events([{u'status': u'confirmed', u'updated': u'2013-12-22T19:49:13.750Z', u'end': {u'dateTime': u'2013-12-23T02:00:00+01:00'}, u'description': u'-60: start_heating.py\n0: turn_music_on.py\n+30: stop_heating.py', u'summary': u'Wakeup', u'start': {u'dateTime': u'2013-12-23T01:00:00+01:00'}, u'id': u'olbia2urfm1ns0h88v4u0d9a5g'}])
Expected:
    [{'commands': [{'exec_time': datetime.datetime(2013, 12, 23, 0, 0), 'command': u'start_heating.py'}, {'exec_time': datetime.datetime(2013, 12, 23, 1, 0), 'command': u'0: turn_music_on.py'}, {'exec_time': datetime.datetime(2013, 12, 23, 1, 30), 'command': u'stop_heating.py'}], 'uid': u'olbia2urfm1ns0h88v4u0d9a5g'}]
Got:
    []
Trying:
    parse_events([{u'status': u'cancelled', u'updated': u'2013-12-22T19:52:50.525Z', u'end': {u'dateTime': u'2013-12-23T02:00:00+01:00'}, u'description': u'-60: start_heating.py\n0: turn_music_on.py\n+30: stop_heating.py', u'summary': u'Wakeup', u'start': {u'dateTime': u'2013-12-23T01:00:00+01:00'}, u'id': u'olbia2urfm1ns0h88v4u0d9a5g'}])
Expecting:
    [{'uid': u'olbia2urfm1ns0h88v4u0d9a5g'}]
ok
17 items had no tests:
    gcalcron
    gcalcron.GCalAdapter
    gcalcron.GCalAdapter.**init**
    gcalcron.GCalAdapter.get_events
    gcalcron.GCalAdapter.queryApi
    gcalcron.GCalCron
    gcalcron.GCalCron.**init**
    gcalcron.GCalCron.clean_settings
    gcalcron.GCalCron.getCalendarId
    gcalcron.GCalCron.init_settings
    gcalcron.GCalCron.load_settings
    gcalcron.GCalCron.reset_settings
    gcalcron.GCalCron.save_settings
    gcalcron.GCalCron.schedule_new_jobs
    gcalcron.GCalCron.sync_gcal_to_cron
    gcalcron.GCalCron.unschedule_old_jobs
    gcalcron.main
3 items passed all tests:
   2 tests in gcalcron.GCalAdapter.get_query
   1 tests in gcalcron.datetime_to_at
   2 tests in gcalcron.parse_commands

---

1 items had failures:
   1 of   2 in gcalcron.parse_events
7 tests in 21 items.
6 passed and 1 failed.
**_Test Failed**_ 1 failures.
root@ubuntu:~/gcalcron# python gcalcron.py
ERROR:root:Sync failed
Traceback (most recent call last):
  File "gcalcron.py", line 420, in main
    g.sync_gcal_to_cron()
  File "gcalcron.py", line 297, in sync_gcal_to_cron
    commandsList = parse_events(events)
  File "gcalcron.py", line 371, in parse_events
    logger.debug(event['id'] + '-' + event['status'] + '-' + event['updated'] + ': ' + unicode(start_time) + ' -> ' + unicode(end_time) + ' (' + event['start']['dateTime'] + ' -> ' + event['end']['dateTime'] + ') ' + '=>' + event['description'])
KeyError: 'description'

**Comment by BenOlley** [comment]
I am recieving the same error above, that I got no response back

[{'commands': [{'exec_time': datetime.datetime(2013, 12, 23, 0, 0), 'command': u'start_heating.py'}, {'exec_time': datetime.datetime(2013, 12, 23, 1, 0), 'command': u'0: turn_music_on.py'}, {'exec_time': datetime.datetime(2013, 12, 23, 1, 30), 'command': u'stop_heating.py'}], 'uid': u'olbia2urfm1ns0h88v4u0d9a5g'}]
Got:
[]

( same as above )

**Comment by fabriceb** [comment]
@codingthefuture : your error is corrected by 303bc79f449ce2fa8cf7719995d5333d8be5bbcb 
It was not a huge issue, the unit test was using a date at the end of 2013, therefore not working since 2014.

@ericleb : your error is corrected by 4e3a82438e16c19e76e4299d1470437ce931a43e
It was not a huge issue, it was only appearing in DEBUG mode

**Comment by ericleb** [comment]
Thanks, works like a charm now,
