### ISSUE TITLE
404 not found - placing client email in double quotes causing this?, single quotes causes cannot be decoded..

### ISSUE THREAD

**Issue by BenOlley** [fabriceb/gcalcron#14]
pi@RUBY ~/gcalcron $ python gcalcron.py
ERROR:root:Sync failed
Traceback (most recent call last):
  File "gcalcron.py", line 420, in main
    g.sync_gcal_to_cron()
  File "gcalcron.py", line 296, in sync_gcal_to_cron
    events = self.gCalAdapter.get_events(sync_start, last_sync, num_days)
  File "gcalcron.py", line 166, in get_events
    return self.queryApi(queries)
  File "gcalcron.py", line 134, in queryApi
    gCalEvents = self.service.events().list(*_query).execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%209b473x5d2xxxxxx9g@group.calendar.google.com/events?orderBy=updated&timeMax=2014-01-22T22%3A27%3A31.942439%2B00%3A00&fields=items%28description%2Cend%2Cid%2Cstart%2Cstatus%2Csummary%2Cupdated%29&singleEvents=true&maxResults=1000&showDeleted=true&timeMin=2014-01-15T22%3A27%3A31.942439%2B00%3A00&alt=json returned "Not Found">

**Comment by BenOlley** [comment]
if anyone can help with this i'd be very grateful

**Comment by fabriceb** [comment]
This is a Google Calendar API issue. Did you download the clients_secrets.json directly on Google? Mine has an empty client_email : 
[...]
"client_email":"",
[...]

and you?

**Comment by fabriceb** [comment]
Since this is not a gcalcron issue, I close the issue.
