### ISSUE TITLE
Added 'end:' support for offsets from end_time

### ISSUE THREAD

**Issue by ndbroadbent** [fabriceb/gcalcron#8]
I've finished this feature, but didn't make a pull request for it yet, because it requires some other pull requests to be accepted first.

As well as `+10:`, `-10:`, you can now also write `end:`, `end +10:`, `end -10:`.

You can see the change here: https://github.com/ndbroadbent/GCalCron2/commit/9b14d5bb9ac2d0755280979e7504a4dc24e099e4

It's on my [support_commands_at_end](https://github.com/ndbroadbent/GCalCron2/tree/support_commands_at_end)  branch, along with the changes to the README.

**Comment by fabriceb** [comment]
I merged it, did not try it yet though.
